### ISSUE TITLE
отут якась дира для SQL інʼєкцій.

### ISSUE THREAD

**Issue by vitaliistupak** [kirill-popov/laravel-pet-project#40]
https://github.com/kirill-popov/laravel-pet-project/blob/068b74fba01f09330d3af466d232670075310260/app/Repositories/ShopRepository.php#LL39C44-L39C49

**Comment by kirill-popov** [comment]
https://laravel.com/docs/10.x/database#running-queries
В документації сказано шо тільки row-queries потрібно захищати від ін'єкцій, всі інші - вже захищені.

https://laravel.com/docs/10.x/queries#basic-where-clauses
код з like в документації
