### ISSUE TITLE
цей рядок теж в сервіс, але без реквесту. Юзера беремо з Illuminate\Auth\AuthManager

### ISSUE THREAD

**Issue by vitaliistupak** [kirill-popov/laravel-pet-project#7]
https://github.com/kirill-popov/laravel-pet-project/blob/068b74fba01f09330d3af466d232670075310260/app/Http/Controllers/UserController.php#LL18C9-L18C40

**Comment by kirill-popov** [comment]
Отак $authManager->guard()->user(); ?
